In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
bullying = pd.read_csv("EMSE_DatosAbiertos.csv")

In [8]:
bullying.info

<bound method DataFrame.info of       sitio  record   q1 texto_q1   q2   texto_q2   q3  \
0        AG       1  3.0  13 años  2.0   Femenino  2.0
1        AG       2  3.0  13 años  2.0   Femenino  2.0
2        AG       3  4.0  14 años  1.0  Masculino  4.0
3        AG       4  6.0  16 años  1.0  Masculino  2.0
4        AG       5  3.0  13 años  2.0   Femenino  2.0
...     ...     ...  ...      ...  ...        ...  ...
56976    AG   57091  6.0  16 años  1.0  Masculino  5.0
56977    AG   57092  6.0  16 años  1.0  Masculino  5.0
56978    AG   57093  6.0  16 años  1.0  Masculino  NaN
56979    AG   57094  6.0  16 años  2.0   Femenino  5.0
56980    AG   57095  6.0  16 años  2.0   Femenino  5.0

                                                texto_q3    q4    q5  ...  \
0      9no grado nivel Primario/Polimodal o 2do año n...   NaN   NaN  ...
1      9no grado nivel Primario/Polimodal o 2do año n...   NaN   NaN  ...
2      2do año/11vo grado nivel Polimodal o 4to año n...  1.67  56.0  ...
3      9no grado nivel Primario/Polimodal o 2do año n...  1.73  70.0  ...
4      9no grado nivel Primario/Polimodal o 2do año n...   NaN   NaN  ...
...                                                  ...   ...   ...  ...
56976  3er año/12vo grado nivel Polimodal o 5to año n...  1.78  86.0  ...
56977  3er año/12vo grado nivel Polimodal o 5to año n...   NaN   NaN  ...
56978                                       Dato perdido   NaN   NaN  ...
56979  3er año/12vo grado nivel Polimodal o 5to año n...   NaN   NaN  ...
56980  3er año/12vo grado nivel Polimodal o 5to año n...  1.65  56.0  ...

       texto_qnpa5g qnpa7g  texto_qnpa7g qnpe3g  texto_qnpe3g qnpe5g  \
0                Si    1.0            Si    2.0            No    2.0
1                Si    2.0            No    2.0            No    2.0
2                Si    2.0            No    2.0            No    2.0
3                No    2.0            No    1.0            Si    1.0
4                No    2.0            No    2.0            No    2.0
...             ...    ...           ...    ...           ...    ...
56976            Si    1.0            Si    1.0            Si    2.0
56977            No    2.0            No    1.0            Si    1.0
56978            Si    2.0            No    2.0            No    2.0
56979            No    2.0            No    2.0            No    2.0
56980            No    2.0            No    1.0            Si    1.0

       texto_qnpe5g  weight    stratum psu
0                No  457.09  201801010  19
1                No  457.09  201801010  19
2                No  261.44  201801010  19
3                Si  550.90  201801010  19
4                No  457.09  201801010  19
...             ...     ...        ...  ..
56976            No   48.28  201824003   5
56977            Si   48.28  201824003   5
56978            No   48.28  201824003   5
56979            No   52.08  201824003   5
56980            Si   52.08  201824003   5

[56981 rows x 309 columns]>

In [7]:
bullying.describe()

,record,q1,q2,q3,q4,q5,q6,q10,q15,q16,...,qnnotb2g,qnbcanyg,qnc1g,qnpa5g,qnpa7g,qnpe3g,qnpe5g,weight,stratum,psu
count,56981.000000,56873.000000,56445.000000,55920.000000,36052.000000,36052.000000,56482.000000,56771.000000,56741.000000,56713.000000,...,55908.000000,19735.000000,19696.000000,55551.000000,55551.000000,55032.000000,55032.000000,56981.000000,5.698100e+04,56981.000000
mean,28535.389832,4.905403,1.520188,3.064485,1.642857,60.212193,1.460448,1.802734,1.361573,1.496447,...,1.208968,1.089891,1.330575,1.701932,1.828428,1.633431,1.687237,46.288166,2.018129e+08,12.438234
std,16479.971553,1.358115,0.499597,1.324451,0.096898,14.723909,0.764121,1.451475,1.079432,1.211089,...,0.406575,0.286033,0.470432,0.457414,0.377011,0.481872,0.463623,80.162741,7.068990e+03,9.378964
min,1.000000,1.000000,1.000000,1.000000,1.200000,27.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.120000,2.018010e+08,1.000000
25%,14263.000000,4.000000,1.000000,2.000000,1.570000,51.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,14.420000,2.018070e+08,6.000000
50%,28522.000000,5.000000,2.000000,3.000000,1.640000,58.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,2.000000,2.000000,2.000000,2.000000,26.370000,2.018130e+08,11.000000
75%,42804.000000,6.000000,2.000000,4.000000,1.700000,66.000000,2.000000,2.000000,1.000000,1.000000,...,1.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,44.780000,2.018200e+08,17.000000
max,57095.000000,8.000000,2.000000,5.000000,2.030000,187.000000,5.000000,8.000000,8.000000,8.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1192.430000,2.018240e+08,57.000000

In [9]:
bullying.shape

(56981, 309)

In [11]:
bullying.columns

Index(['sitio', 'record', 'q1', 'texto_q1', 'q2', 'texto_q2', 'q3', 'texto_q3',
       'q4', 'q5',
       ...
       'texto_qnpa5g', 'qnpa7g', 'texto_qnpa7g', 'qnpe3g', 'texto_qnpe3g',
       'qnpe5g', 'texto_qnpe5g', 'weight', 'stratum', 'psu'],
      dtype='object', length=309)